// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCexcbEQ0a2NSleohRs2xrjC6xXaSx-2vc',
    appId: '1:435629787312:web:d98b9c4903b008c3241375',
    messagingSenderId: '435629787312',
    projectId: 'ifa-21312103',
    authDomain: 'ifa-21312103.firebaseapp.com',
    storageBucket: 'ifa-21312103.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB912bAB-e8klZcMqrhutlaZoAD_Xum8IQ',
    appId: '1:435629787312:android:d2cc3394da7c00fa241375',
    messagingSenderId: '435629787312',
    projectId: 'ifa-21312103',
    storageBucket: 'ifa-21312103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjvfPNvT6axkkw2IsEQFTMxNK5t4vD2hU',
    appId: '1:435629787312:ios:ab98f00419806874241375',
    messagingSenderId: '435629787312',
    projectId: 'ifa-21312103',
    storageBucket: 'ifa-21312103.appspot.com',
    iosBundleId: 'com.ifa.ifa21312103',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjvfPNvT6axkkw2IsEQFTMxNK5t4vD2hU',
    appId: '1:435629787312:ios:05768b72647e94f4241375',
    messagingSenderId: '435629787312',
    projectId: 'ifa-21312103',
    storageBucket: 'ifa-21312103.appspot.com',
    iosBundleId: 'com.ifa.ifa21312103.RunnerTests',
  );
}
